// Default values for AdminAnnouncements form

const DEFAULTS = {
    id: '', title: '', title2: '', title3: '', speaker: '', content: '', tag: 'GALA', date: '', time: '',
    format: 'instagram',
    bgMode: 'gradient',
    bgImage: null,
    bgPosX: 50,
    bgPosY: 50,
    gradientStart: '#1a1a2e',
    gradientEnd: '#16213e',
    blendGradient: false,
    blendOpacity: 0.5,
    bgOpacity: 0.55,
    showLogoOasis: true,
    showLogoIasd: false,
    showRrss: false,
    logoOasisSize: 40,
    logoIasdSize: 30,
    rrssSize: 28,
    customLogos: [], // Array of {name, url}
    titlePos: { x: 0, y: 108 },
    title2Pos: { x: 0, y: 104 },
    title3Pos: { x: 0, y: 100 },
    speakerPos: { x: 0, y: 100 },
    tagPos: { x: 0, y: 51 },
    datePos: { x: 0, y: 0 },
    timePos: { x: 0, y: 0 },
    locationPos: { x: 0, y: 0 },
    contentPos: { x: 0, y: 0 },
    rrssPos: { x: 0, y: 0 },
    location: 'TEMPLO OASIS',
    locationSize: 1,
    titleSize: 2,
    title2Size: 1.5,
    title3Size: 1.2,
    speakerSize: 1.7,
    contentSize: 1.8,
    tagSize: 0.5,
    dateSize: 1,
    timeSize: 1,
    tagStyle: 'pill-translucent',
    contentStyle: 'normal',
    contentPattern: 'none', // none, dots, grain, lines
    contentBgOpacity: 0.15,
    titleFont: 'MoonRising',
    title2Font: 'ModernAge',
    title3Font: 'AdventSans',
    speakerFont: 'above-the-beyond-script',
    contentFont: 'ModernAge',
    tagFont: 'AdventSans',
    dateFont: 'AdventSans',
    timeFont: 'AdventSans',
    locationFont: 'AdventSans',
    // Colors with opacity
    titleColor: '#ffffff',
    title2Color: '#ffffff',
    title3Color: '#ffffff',
    speakerColor: '#ffffff',
    tagColor: '#ffffff',
    tagBgColor: '#5b2ea6',
    tagBorderColor: '#ffffff',
    dateColor: '#ffffff',
    timeColor: '#ffffff',
    locationColor: '#ffffff',
    // Opacity per element (0-100)
    titleOpacity: 100,
    title2Opacity: 100,
    title3Opacity: 100,
    speakerOpacity: 100,
    tagOpacity: 100,
    dateOpacity: 100,
    timeOpacity: 100,
    locationOpacity: 100,
};

export default DEFAULTS;
